plugins { id 'com.android.application' }

android {
    namespace 'com.explapp.kidslegacy'
    compileSdk 33

    defaultConfig {
        applicationId 'com.explapp.kidslegacy'
        minSdk 19
        targetSdk 28
        versionCode 3
        versionName '3.0.0-illustrated'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }
}
