import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
void main(){WidgetsFlutterBinding.ensureInitialized();SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);runApp(const KidsApp());}
const MethodChannel _audio=MethodChannel('kids_audio');
Future<void> play(String f) async{try{await _audio.invokeMethod('playAsset',{'file':'assets/audio/$f'});}catch(_){SystemSound.play(SystemSoundType.click);}HapticFeedback.selectionClick();}
class KidsApp extends StatelessWidget{const KidsApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(title:'طفلي الأول',debugShowCheckedModeBanner:false,theme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xff6C63FF)),scaffoldBackgroundColor:const Color(0xffFFF8EA),appBarTheme:const AppBarTheme(centerTitle:true,backgroundColor:Color(0xffFFF8EA),foregroundColor:Color(0xff222222))),home:const HomePage());}
class LearnItem{final String title,sub,emoji,sound;const LearnItem(this.title,this.sub,this.emoji,this.sound);} 
const arLetters=[LearnItem('أ','أسد','🦁','ar_letter.wav'),LearnItem('ب','بطة','🦆','ar_letter.wav'),LearnItem('ت','تفاحة','🍎','ar_letter.wav'),LearnItem('ث','ثعلب','🦊','ar_letter.wav'),LearnItem('ج','جمل','🐪','ar_letter.wav'),LearnItem('ح','حصان','🐴','ar_letter.wav'),LearnItem('خ','خروف','🐑','ar_letter.wav'),LearnItem('د','دجاجة','🐔','ar_letter.wav'),LearnItem('ذ','ذرة','🌽','ar_letter.wav'),LearnItem('ر','رمان','🍎','ar_letter.wav'),LearnItem('ز','زرافة','🦒','ar_letter.wav'),LearnItem('س','سمكة','🐟','ar_letter.wav'),LearnItem('ش','شمس','☀️','ar_letter.wav'),LearnItem('ص','صقر','🦅','ar_letter.wav'),LearnItem('ض','ضفدع','🐸','ar_letter.wav'),LearnItem('ط','طائرة','✈️','ar_letter.wav'),LearnItem('ظ','ظرف','✉️','ar_letter.wav'),LearnItem('ع','عصفور','🐦','ar_letter.wav'),LearnItem('غ','غزال','🦌','ar_letter.wav'),LearnItem('ف','فيل','🐘','ar_letter.wav'),LearnItem('ق','قطة','🐱','ar_letter.wav'),LearnItem('ك','كلب','🐶','ar_letter.wav'),LearnItem('ل','ليمون','🍋','ar_letter.wav'),LearnItem('م','موز','🍌','ar_letter.wav'),LearnItem('ن','نمر','🐯','ar_letter.wav'),LearnItem('هـ','هلال','🌙','ar_letter.wav'),LearnItem('و','وردة','🌹','ar_letter.wav'),LearnItem('ي','يد','✋','ar_letter.wav')];
const enLetters=[LearnItem('A','Apple','🍎','en_letter.wav'),LearnItem('B','Ball','⚽','en_letter.wav'),LearnItem('C','Cat','🐱','en_letter.wav'),LearnItem('D','Dog','🐶','en_letter.wav'),LearnItem('E','Elephant','🐘','en_letter.wav'),LearnItem('F','Fish','🐟','en_letter.wav'),LearnItem('G','Giraffe','🦒','en_letter.wav'),LearnItem('H','Horse','🐴','en_letter.wav'),LearnItem('I','Ice Cream','🍦','en_letter.wav'),LearnItem('J','Juice','🧃','en_letter.wav'),LearnItem('K','Kite','🪁','en_letter.wav'),LearnItem('L','Lion','🦁','en_letter.wav'),LearnItem('M','Monkey','🐒','en_letter.wav'),LearnItem('N','Nest','🪺','en_letter.wav'),LearnItem('O','Orange','🍊','en_letter.wav'),LearnItem('P','Panda','🐼','en_letter.wav'),LearnItem('Q','Queen','👑','en_letter.wav'),LearnItem('R','Rabbit','🐰','en_letter.wav'),LearnItem('S','Sun','☀️','en_letter.wav'),LearnItem('T','Tiger','🐯','en_letter.wav'),LearnItem('U','Umbrella','☂️','en_letter.wav'),LearnItem('V','Van','🚐','en_letter.wav'),LearnItem('W','Water','💧','en_letter.wav'),LearnItem('X','Xylophone','🎼','en_letter.wav'),LearnItem('Y','Yo-yo','🪀','en_letter.wav'),LearnItem('Z','Zebra','🦓','en_letter.wav')];
const arNums=[LearnItem('1','واحد','⭐','number.wav'),LearnItem('2','اثنان','⭐⭐','number.wav'),LearnItem('3','ثلاثة','⭐⭐⭐','number.wav'),LearnItem('4','أربعة','⭐⭐⭐⭐','number.wav'),LearnItem('5','خمسة','⭐⭐⭐⭐⭐','number.wav'),LearnItem('6','ستة','🍎🍎🍎🍎🍎🍎','number.wav'),LearnItem('7','سبعة','🍎🍎🍎🍎🍎🍎🍎','number.wav'),LearnItem('8','ثمانية','🍎🍎🍎🍎🍎🍎🍎🍎','number.wav'),LearnItem('9','تسعة','🍎🍎🍎🍎🍎🍎🍎🍎🍎','number.wav'),LearnItem('10','عشرة','🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎','number.wav')];
const enNums=[LearnItem('1','One','⭐','number.wav'),LearnItem('2','Two','⭐⭐','number.wav'),LearnItem('3','Three','⭐⭐⭐','number.wav'),LearnItem('4','Four','⭐⭐⭐⭐','number.wav'),LearnItem('5','Five','⭐⭐⭐⭐⭐','number.wav'),LearnItem('6','Six','🍎🍎🍎🍎🍎🍎','number.wav'),LearnItem('7','Seven','🍎🍎🍎🍎🍎🍎🍎','number.wav'),LearnItem('8','Eight','🍎🍎🍎🍎🍎🍎🍎🍎','number.wav'),LearnItem('9','Nine','🍎🍎🍎🍎🍎🍎🍎🍎🍎','number.wav'),LearnItem('10','Ten','🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎','number.wav')];
const arColors=[LearnItem('أحمر','','🔴','color.wav'),LearnItem('أزرق','','🔵','color.wav'),LearnItem('أخضر','','🟢','color.wav'),LearnItem('أصفر','','🟡','color.wav'),LearnItem('أسود','','⚫','color.wav'),LearnItem('أبيض','','⚪','color.wav'),LearnItem('بني','','🟤','color.wav'),LearnItem('بنفسجي','','🟣','color.wav')];
const enColors=[LearnItem('Red','','🔴','color.wav'),LearnItem('Blue','','🔵','color.wav'),LearnItem('Green','','🟢','color.wav'),LearnItem('Yellow','','🟡','color.wav'),LearnItem('Black','','⚫','color.wav'),LearnItem('White','','⚪','color.wav'),LearnItem('Brown','','🟤','color.wav'),LearnItem('Purple','','🟣','color.wav')];
const animals=[LearnItem('أسد','Lion','🦁','animal.wav'),LearnItem('فيل','Elephant','🐘','animal.wav'),LearnItem('قطة','Cat','🐱','animal.wav'),LearnItem('كلب','Dog','🐶','animal.wav'),LearnItem('حصان','Horse','🐴','animal.wav'),LearnItem('أرنب','Rabbit','🐰','animal.wav'),LearnItem('بقرة','Cow','🐮','animal.wav'),LearnItem('قرد','Monkey','🐒','animal.wav'),LearnItem('زرافة','Giraffe','🦒','animal.wav'),LearnItem('نمر','Tiger','🐯','animal.wav'),LearnItem('دب','Bear','🐻','animal.wav'),LearnItem('سمكة','Fish','🐟','animal.wav')];
class HomePage extends StatelessWidget{const HomePage({super.key});void open(BuildContext c,Widget p){play('tap.wav');Navigator.push(c,MaterialPageRoute(builder:(_)=>p));}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('طفلي الأول')),body:SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[const Text('تعلم والعب',textAlign:TextAlign.center,style:TextStyle(fontSize:36,fontWeight:FontWeight.w900)),const SizedBox(height:14),HomeButton('🇸🇦','العربية',()=>open(c,const ArabicPage())),HomeButton('🇬🇧','English',()=>open(c,const EnglishPage())),HomeButton('🐶','الحيوانات عربي + English',()=>open(c,const LearnGrid(title:'الحيوانات',items:animals,rtl:true))),HomeButton('🎮','الألعاب',()=>open(c,const GamesPage()))]))));}
class HomeButton extends StatelessWidget{final String icon,text;final VoidCallback onTap;const HomeButton(this.icon,this.text,this.onTap,{super.key});@override Widget build(BuildContext c)=>Card(margin:const EdgeInsets.only(bottom:14),elevation:2,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(24)),child:InkWell(borderRadius:BorderRadius.circular(24),onTap:onTap,child:Padding(padding:const EdgeInsets.all(22),child:Row(children:[Text(icon,style:const TextStyle(fontSize:42)),const SizedBox(width:18),Expanded(child:Text(text,style:const TextStyle(fontSize:26,fontWeight:FontWeight.bold)))])))) ;}
class ArabicPage extends StatelessWidget{const ArabicPage({super.key});void open(BuildContext c,Widget p){play('tap.wav');Navigator.push(c,MaterialPageRoute(builder:(_)=>p));}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('العربية')),body:ListView(padding:const EdgeInsets.all(16),children:[HomeButton('🔤','الحروف العربية',()=>open(c,const LearnGrid(title:'الحروف العربية',items:arLetters,rtl:true))),HomeButton('🔢','الأرقام 1 - 10',()=>open(c,const LearnGrid(title:'الأرقام',items:arNums,rtl:true))),HomeButton('🎨','الألوان',()=>open(c,const LearnGrid(title:'الألوان',items:arColors,rtl:true))),HomeButton('🐾','الحيوانات',()=>open(c,const LearnGrid(title:'الحيوانات',items:animals,rtl:true)))])));}
class EnglishPage extends StatelessWidget{const EnglishPage({super.key});void open(BuildContext c,Widget p){play('tap.wav');Navigator.push(c,MaterialPageRoute(builder:(_)=>p));}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('English')),body:ListView(padding:const EdgeInsets.all(16),children:[HomeButton('🔠','Capital Letters',()=>open(c,const LearnGrid(title:'Capital Letters',items:enLetters,rtl:false))),HomeButton('🔢','Numbers 1 - 10',()=>open(c,const LearnGrid(title:'Numbers',items:enNums,rtl:false))),HomeButton('🎨','Colors',()=>open(c,const LearnGrid(title:'Colors',items:enColors,rtl:false))),HomeButton('🐾','Animals',()=>open(c,const LearnGrid(title:'Animals',items:animals,rtl:false)))]));}
class LearnGrid extends StatelessWidget{final String title;final List<LearnItem> items;final bool rtl;const LearnGrid({super.key,required this.title,required this.items,required this.rtl});@override Widget build(BuildContext c)=>Directionality(textDirection:rtl?TextDirection.rtl:TextDirection.ltr,child:Scaffold(appBar:AppBar(title:Text(title)),body:GridView.builder(padding:const EdgeInsets.all(12),itemCount:items.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,mainAxisSpacing:12,crossAxisSpacing:12,childAspectRatio:.88),itemBuilder:(_,i)=>LearnCard(items[i]))));}
class LearnCard extends StatelessWidget{final LearnItem item;const LearnCard(this.item,{super.key});@override Widget build(BuildContext c)=>Card(color:Colors.white,elevation:2,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(26)),child:InkWell(borderRadius:BorderRadius.circular(26),onTap:()=>play(item.sound),child:Padding(padding:const EdgeInsets.all(12),child:FittedBox(fit:BoxFit.scaleDown,child:Column(mainAxisSize:MainAxisSize.min,children:[Text(item.emoji,style:const TextStyle(fontSize:58)),const SizedBox(height:10),Text(item.title,textAlign:TextAlign.center,style:const TextStyle(fontSize:36,fontWeight:FontWeight.w900)),if(item.sub.isNotEmpty)...[const SizedBox(height:6),Text(item.sub,textAlign:TextAlign.center,style:const TextStyle(fontSize:25,fontWeight:FontWeight.bold,color:Color(0xff555555)))]])))));}
class GamesPage extends StatefulWidget{const GamesPage({super.key});@override State<GamesPage> createState()=>_GamesPageState();}
class _GamesPageState extends State<GamesPage>{int stars=0;String msg='اختر الأسد';void ans(bool ok){play(ok?'success.wav':'wrong.wav');setState((){if(ok){stars++;msg='أحسنت ⭐';}else{msg='حاول مرة أخرى';}});}@override Widget build(BuildContext c){final opts=animals.take(4).toList();return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text('الألعاب  ⭐ $stars')),body:Padding(padding:const EdgeInsets.all(16),child:Column(children:[Text(msg,textAlign:TextAlign.center,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:18),Expanded(child:GridView.builder(itemCount:opts.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,mainAxisSpacing:12,crossAxisSpacing:12),itemBuilder:(_,i){final it=opts[i];return Card(color:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(26)),child:InkWell(borderRadius:BorderRadius.circular(26),onTap:()=>ans(it.title=='أسد'),child:Center(child:Text(it.emoji,style:const TextStyle(fontSize:74)))));}))]))));}}
